M48
; DRILL file {KiCad 9.0.5} date 2026-03-11T17:06:26+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-11T17:06:26+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.991
%
G90
G05
T1
X50.32Y28.89
X50.32Y23.11
T2
X14.75Y43.5
X17.75Y43.5
T3
X20.96Y36.25
X26.04Y37.266
X26.04Y35.234
M30
